### ISSUE TITLE
Need better README

### ISSUE THREAD

**Issue by boratanrikulu** [berkayalcin/Computer-Vision-Application-From-Scratch#1]
It's painful to check the codes because you have to go in and out directories. You might want write a main README to avoid this.

Like this one:

| Subject | Code |
|:---------:|:-------:|
| **Color Histogram**  | [**`color_histogram`**](https://github.com/berkayalcin/Computer-Vision-Application-From-Scratch/tree/master/Feature_Extraction/color_histogram) |
| **Color Space** | [**`hgv_color_space`**](https://github.com/berkayalcin/Computer-Vision-Application-From-Scratch/tree/master/Feature_Extraction/color_space) | 
| ... | ... | ... |
| ... | ... | ... |

**Comment by berkayalcin** [comment]
I'll take care of it thanks for warning 👍
